# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'blabla' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for blabla

  target 'blabla-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'blablaTests' do
    inherit! :search_paths
    # Pods for testing
  end
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'
end

# target 'blabla-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for blabla-tvOS

#   target 'blabla-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
