const FETCH_LOGIN = "FETCH_LOGIN"
const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS"
const FETCH_LOGIN_FAIL = "FETCH_LOGIN_SUCCESS"

const LOGIN_TYPE = {
    FETCH_LOGIN,
    FETCH_LOGIN_FAIL,
    FETCH_LOGIN_SUCCESS
}
export default LOGIN_TYPE